### ISSUE TITLE
Invalid server crash

### ISSUE THREAD

**Issue by Kieaer** [shugen002/MDTSteamLobbyPlugin#1]
```
[06-26-2021 05:08:02] [I] lobby 111814365: 404871931 caused 404871931's change: Entered
[06-26-2021 05:08:02] [I] Connection request: 404871931
[06-26-2021 05:08:02] [I] Am server, accepting request from 404871931 true
[06-26-2021 05:08:08] [I] Create STEAM client 404871931
[06-26-2021 05:08:08] [I] Received STEAM connection: steam:404871931
[06-26-2021 05:08:08] [E] java.lang.NoSuchMethodError: 'void mindustry.net.Net.handleServerReceived(mindustry.net.NetConnection, java.lang.Object)'
        at space.shugen.MDTSteamLobbyPlugin.SNet$1.update(SNet.java:85)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)

[06-26-2021 05:08:23] [I] lobby 111814365: 404871931 caused 404871931's change: Left
Exception in thread "HeadlessApplication" java.lang.NoSuchMethodError: 'void mindustry.net.Net.handleServerReceived(mindustry.net.NetConnection, java.lang.Object)'
        at space.shugen.MDTSteamLobbyPlugin.SNet.disconnectSteamUser(SNet.java:247)
        at space.shugen.MDTSteamLobbyPlugin.SNet.onLobbyChatUpdate(SNet.java:282)
        at com.codedisaster.steamworks.SteamMatchmakingCallbackAdapter.onLobbyChatUpdate(SteamMatchmakingCallbackAdapter.java:36)
        at com.codedisaster.steamworks.SteamAPI.runCallbacks(Native Method)
        at space.shugen.MDTSteamLobbyPlugin.MDTSteamLobbyPlugin$2.update(MDTSteamLobbyPlugin.java:112)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:89)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
[06-26-2021 05:08:31] [E] java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract void send(java.lang.Object, boolean)' of abstract class mindustry.net.NetConnection.
        at mindustry.net.Net.send(Net.java:225)
        at mindustry.gen.Call.sendMessage(Call.java:783)
        at mindustry.core.NetServer.onDisconnect(NetServer.java:523)
        at mindustry.core.NetServer.lambda$new$3(NetServer.java:92)
        at mindustry.net.Net.handleServerReceived(Net.java:303)
        at mindustry.net.ArcNetProvider$2.lambda$disconnected$1(ArcNetProvider.java:116)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
        ```

**Comment by shugen002** [comment]
try this build with any version after https://github.com/Anuken/Mindustry/commit/eaeb67b91f173a508c1da206df5183767d1b3ebb
https://github.com/shugen002/MDTSteamLobbyPlugin/actions/runs/973437991

**Comment by Kieaer** [comment]
![image](https://user-images.githubusercontent.com/44261958/125183720-d5ad4f00-e253-11eb-8e20-0b8e438f19f6.png)

@shugen002 Doesn't work on 127.3 (7.0 pre-alpha)
